spring.application.name=upimesh
# Server
server.port=8080

#  PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://ep-autumn-dew-apwpjaer-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#  JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# --- Redis Connection ---
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=6379

# --- Kafka Configuration ---
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Producer & Consumer Settings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# --- Fast2SMS Configuration ---
# These values are injected from your .env via Docker
fast2sms.api.key=${FAST2SMS_API_KEY}
my.mobile.number=${MY_MOBILE_NUMBER}

# --- JavaMail (Gmail SMTP) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# The recipient address for alerts
my.email.address=${MY_EMAIL_ADDRESS}
# Add this to application.properties
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# --- Business Logic & Logging ---
upi.mesh.idempotency-ttl-seconds=86400
logging.level.com.payment.upimesh=INFO